server:
  port: 8080
spring:
  profiles:
    active: @spring.active@
  application:
    name: dream-api
  #  数据库设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  dinger:
    project-id: ${spring.application.name}
    dingers:
      # 使用钉钉机器人, 请根据自己机器人配置信息进行修改
      dingtalk:
        tokenId: xxx  # 钉钉 tokenId
        secret: xxx   # 钉钉 secret
  mail:
    host: smtp.qiye.aliyun.com # smtp服务器地址
    username: xxx  # 邮箱地址
    password: xxx  # 开启 POP3 之后设置的客户端授权码
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  freemarker:
    cache: false
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/webapp/
    checkTemplateLocation: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis Plus Config
mybatis-plus:
  global-config:
    banner: false

# 项目设置
dream-api:
  # 是否展示 helloController 中的接口（默认展示）
  show-hello: true
  # IP 访问策略 （white、black、none）
  access-strategy: none
  # 白名单列表（仅在白名单策略时生效）
  white-list:
    - 127.0.0.1
    - 192.168.1.195

