spring:
  #  数据库设置
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/dream?autoReconnect=true\
          &useUnicode=true&characterEncoding=utf8\
          &zeroDateTimeBehavior=CONVERT_TO_NULL\
          &useSSL=false&serverTimezone=Asia/Shanghai\
          &nullCatalogMeansCurrent=true"
    username: vchao
    password: vchao123
