version: "3"

services:

  mysql:
    container_name: mysql
    build:
      context: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Pa33word
    networks:
      - dream

  java:
    container_name: java
    build:
      context: java
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - dream

networks:
  dream: